Sppages1.0.1/Sppages.UserInterface/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Invoice.Service.Interface;
using Microsoft.AspNetCore.Mvc;
using Sppages.Business.Derived;
using Sppages.Model.Factories;
using Sppages.Model.Master;

namespace Sppages.UserInterface.Controllers
{
    public class SearchController : Controller
    {
        private readonly BllFrontEnd _bllFrontEnd;

        public SearchController(IFrontEndService iFrontEndService, IModelFactory iModelFactory)
        {
            _bllFrontEnd = new BllFrontEnd(iFrontEndService, iModelFactory);
        }

        public ActionResult Index(string SearchBy, string Id)
        {
            ViewBag.SearchBy = SearchBy;
            ViewBag.Id = Id;
            return View();
        }

        [HttpGet]
        public async Task<JsonResult> SearchAd(int PageSize, int PageNo, string SearchString, string SearchBy, string Id)
        {
            try
            {
                var val = await _bllFrontEnd.SearchAdByLocTag(PageSize, PageNo, SearchString, SearchBy, Id);
                return Json(new
                {
                    Success = true,
                    Value = (List<LocSummaryModel>)val.Data,
                    TotalRowsCount = val.TotalRowsCount
                });
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    Success = false
                });
            }
        }

        [HttpGet]
        public async Task<JsonResult> SearchPost(string SearchBy, string Id)
        {
            var location = await _bllFrontEnd.SearchPost(SearchBy, Id);
            return Json(new
            {
                Success = true,
                Value = location
            });
        }

    }
}

Sppages1.0.1/Sppages.UserInterface/Views/Search/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_LayoutWithoutMenu.cshtml";
}

<input type="hidden" id="SearchBy" value="@ViewBag.SearchBy" />
<input type="hidden" id="Id" value="@ViewBag.Id" />

<div id="boxes" class="fullwidth masoned"  ng-controller="homePageCtrl" style="position: relative; height: 360px; padding-left: 4%;">
    <div class="col-md-11 form-group">
        <input type="text" ng-model="searchString" ng-keyup="setSearchString()" class="form-control" placeholder="Type your search keyword.." style="color: white; background-color: #2C2C2C;">
    </div>
    <div dir-paginate="adPost in getAdPostList|orderBy:'title'|itemsPerPage:$root.itemViewPerPage" total-items="totalItemCount" class="entry small box_view ng-scope" style="height: 280px !important;">
        <div class="thumbnail1">
            <a href="/Profile/Index/{{adPost.id}}">
                <img src="/ApplicationImage/AdPost/{{adPost.featuredImage}}" width="222" height="180">
                <span class="overlay"></span>
            </a>
            <div class="category">
                <ul class="post-categories">
                    <li>
                        <a href="/Search/Index/{{adPost.locationId}}?SearchBy=Location" rel="category tag">{{adPost.locationName}}</a>
                    </li>
                </ul>
            </div>
            <span class="month">{{adPost.month}}<span class="date">{{adPost.day}}</span></span>
        </div>
        <h2 class="title">
            <a href="/Profile/Index/{{adPost.id}}">{{adPost.name}}</a>
        </h2>
        <p class="postinfo">
            posted by<a href="#" title="Posts by admin" rel="author">admin</a>
        </p>
    </div>
</div>
<div class=" row col-md-12 col-lg-12 align-content-lg-center align-items-lg-center text-center center">
    <div class="col-md-3 col-lg-3"></div>
    <div class="col-md-3 col-lg-6">
        <dir-pagination-controls max-size="5"
                                 direction-links="true"
                                 boundary-links="true" on-page-change="getPageNo(newPageNumber)">
        </dir-pagination-controls>
    </div>
    <div class="col-md-3 col-lg-3 row">
        <div class="col-md-8 col-lg-8"></div>
        <div class="col-md-4 col-lg-4">
            <select ng-model="viewPerPage" class="form-control" ng-change="setViewPerPage(viewPerPage)"  style="color: white; background-color: #2C2C2C;">
                <option value="5">5</option>
                <option value="10">10</option>
                <option value="15">15</option>
                <option value="20">20</option>
            </select>
        </div>
    </div>
</div>

@*<div id="content" class="clearfix" ng-controller="homePageCtrl">
        <div id="boxes" class="fullwidth masoned" style="position: relative; height: 360px; padding-left: 4%;">
            <div ng-mouseover="makeTall($event)" ng-repeat="adPost in getAdPostList |orderBy:publishDate" class="entry small box_view" style="height: 280px !important;">
                <div class="thumbnail1">
                    <a href="/Profile/Index/{{adPost.id}}">
                        <img src="/ApplicationImage/AdPost/{{adPost.featuredImage}}" width="222" height="180">
                        <span class="overlay"></span>
                    </a>
                    <div class="category">
                        <ul class="post-categories">
                            <li>
                                <a href="/Search/Index/{{adPost.locationId}}?SearchBy=Location" rel="category tag">{{adPost.locationName}}</a>
                            </li>
                        </ul>
                    </div>
                    <span class="month">{{adPost.month}}<span class="date">{{adPost.day}}</span></span>
                </div>
                <h2 class="title">
                    <a href="/Profile/Index/{{adPost.id}}">{{adPost.name}}</a>
                </h2>
                <p class="postinfo">
                    posted by<a href="#" title="Posts by admin" rel="author">admin</a>
                </p>
            </div>
        </div>
    </div>*@

@section page_styles {
    <style type="text/css">
        .box_view {
            margin-left: 1%;
            top: 0px;
            z-index: 1;
            /*opacity: 0.3;*/
        }
    </style>
}

@section Scripts {
    <script src="~/js/application/search-page.js"></script>
    <script type="text/javascript" src="~/Theme/Scripts/jquery.hoverIntent.minified.js"></script>

    <script type="text/javascript">
        jQuery(document).ready(function () {
            //GetPost();
        });

        function GetPost() {
            //Metronic.blockUI();
            var options = $("#boxes");
            $.ajax({
                type: "GET",
                cache: false,
                url: "@(@Url.Action("SearchPost", "Search", new {SearchBy = ViewBag.SearchBy, Id = ViewBag.Id }))",
                data: {},
                dataType: "json",
                contentType: "application/json",
                success: function (val) {
                    var result = val.value;
                    $.each(result, function () {

                        var gPost = '<div class="entry small box_view">' +
                         '<div class="thumbnail1">' +
                         '<a href="/Profile/Index/' + this.id + '">' +
                         '<img src="/ApplicationImage/AdPost/' + this.featuredImage + '" width="222" height="180"/>' +
                         '<span class="overlay"></span>' +
                         '</a>' +
                         '<div class="category">' +
                         '<ul class="post-categories">' +
                         '<li>' +
                         '<a href="/Search/Index/' + this.locationId + '?SearchBy=Location" rel="category tag">' + this.locationName + '</a>' +
                         '</li>' +
                         '</ul>' +
                         '</div>' +
                         '<span class="month">' + this.month + '<span class="date">' + this.day + '</span></span>' +
                         '</div>' +
                         '<h2 class="title">' +
                         '<a href="/Profile/Index/' + this.id + '">' + this.name + '</a>' +
                         '</h2>' +
                         '<p class="postinfo">posted by' +
                         '<a href="#" title="Posts by admin" rel="author">admin</a>' +
                         '</p>' +
                         '<div class="entry-content">' +
                         '<div class="bottom-bg">' +
                         '<div class="excerpt" style="height: 75px;">' +
                         '<p>' + this.longDescription + '</p>' +
                         '<div class="textright">' +
                         '<a href="/Profile/Index/' + this.id + '" class="readmore">' +
                         '<span>»</span>»' +
                         '</a>' +
                         '</div>' +
                         '</div>' +
                         '</div>' +
                         '</div>' +
                         '</div>';
                        options.append(gPost);

                    });

                    //Metronic.unblockUI();
                    jQuery(".entry").hoverIntent({
                        over: makeTall,
                        timeout: 100,
                        out: makeShort
                    });
                },
                error: function (error) {
                    //Metronic.unblockUI();
                    var msg = 'Fail to load post';
                    alert(msg);
                }
            });
        }

        function makeTall() {
            jQuery(this).addClass('active');//.css('z-index', '7').find('.bottom-bg .excerpt').animate({ "height": 200 }, 200);
            jQuery('.entry').not(this).animate({ opacity: 0.3 }, 200);
        }

        function makeShort() {
            jQuery(this).css('z-index', '1');//.find('.bottom-bg .excerpt').animate({ "height": 75 }, 200);
            jQuery('.entry').removeClass('active').animate({ opacity: 1 }, 200);
        }

    </script>
}