Sppages1.0.1/Sppages.UserInterface/Areas/Master/Controllers/TagController.cs
using System;
using System.Security.Claims;
using System.Threading.Tasks;
using Invoice.Service.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Sppages.Business.Derived;
using Sppages.Business.Utility;
using Sppages.Model.Factories;
using Sppages.Model.Master;

namespace Sppages.UserInterface.Areas.Master.Controllers
{
    [Area("Master")]
    [Authorize(Roles = "SMAdmin, Admin")]
    public class TagController : Controller
    {
        private readonly BllTag _bllTag;

        public TagController(IMasterService iMasterService, IModelFactory iModelFactory)
        {
            _bllTag = new BllTag(iMasterService, iModelFactory);
        }

        public async Task<IActionResult> Index()
        {
            //var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value; // will give the user's userId
            //var userName = User.FindFirst(ClaimTypes.Name).Value; // will give the user's userName
            //var userEmail = User.FindFirst(ClaimTypes.Email).Value; // will give the user's Email
            //ViewBag.LoadParent=LoadParent();
            //ViewBag.LoadLocation=LoadLocation();
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> GetTagList(IFormCollection formFields)
        {
            return Json(await _bllTag.GetTagList(formFields));
        }

        [HttpGet]
        public async Task<JsonResult> GetTag(string Id)
        {
            var tag = await _bllTag.GetTag(Id);
            return Json(new
            {
                Success = true,
                Value = tag
            });
        }

        [HttpPost]
        public async Task<JsonResult> InsertUpdate(TagModel tagModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (tagModel.Id != null)
                    {
                        tagModel.ModifiedBy = User.FindFirst(ClaimTypes.Name).Value;
                        await _bllTag.Update(tagModel);
                    }
                    else
                    {
                        tagModel.Id = await _bllTag.GetTagId();
                        tagModel.CreatedBy = User.FindFirst(ClaimTypes.Name).Value;
                        await _bllTag.Insert(tagModel);
                    }
                    return Json(new { success = true, Message = MessageManager.TAG_SAVE_SUCCESS_MESSAGE });
                }
                catch (Exception ex)
                {
                    return Json(new { success = false, Message = MessageManager.TAG_SAVE_FAIL_MESSAGE });
                }
            }
            return Json(new {success = false, Message = MessageManager.TAG_SAVE_FAIL_MESSAGE});
        }

        [HttpDelete]
        public async Task<JsonResult> Delete(string Id)
        {
            try
            {
                var result = await _bllTag.Delete(Id);
                if (result)
                    return Json(new
                    {
                        Success = true,
                        Message = MessageManager.TAG_DELETE_SUCCESS_MESSAGE
                    });
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    Success = false,
                    Message = MessageManager.TAG_DELETE_FAIL_MESSAGE
                });
            }

            return Json(new
            {
                Success = false,
                Message = MessageManager.TAG_DELETE_FAIL_MESSAGE
            });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                // db.Dispose();
            }
            base.Dispose(disposing);
        }
        
    }
}

Sppages1.0.1/Sppages.UserInterface/Areas/Master/Views/Tag/Index.cshtml
@model IEnumerable<Sppages.Model.Master.TagModel>
    @{
        ViewBag.Title = "Tag Management";
        Layout = "_LayoutBackEnd";
    }

    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        @ViewBag.Title
                    </h3>
                </div>
            </div>
            <div class="m-portlet__head-tools">
                <ul class="m-portlet__nav"><li class="m-portlet__nav-item"></li></ul>
            </div>
        </div>

        <div class="m-portlet__body">

            <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
                <div class="row align-items-center">
                    <div class="col-xl-8 order-2 order-xl-1">
                        <div class="form-group m-form__group row align-items-center">
                            <div class="col-md-4">
                                <div class="m-form__group m-form__group--inline">
                                    <div class="m-form__label">
                                        <label>Status:</label>
                                    </div>
                                    <div class="m-form__control">
                                        <select class="form-control m-bootstrap-select1" id="m_form_status">
                                            <option value="All">All</option>
                                            <option value="Active">Active</option>
                                            <option value="Inactive">Inactive</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="d-md-none m--margin-bottom-10"></div>
                            </div>

                            <div class="col-md-4">
                                <div class="m-input-icon m-input-icon--left">
                                    <input type="text" class="form-control m-input" placeholder="Search..." id="generalSearch">
                                    <span class="m-input-icon__icon m-input-icon__icon--left">
                                        <span><i class="la la-search"></i></span>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-4 order-1 order-xl-2 m--align-right">
                        <a href="#" class="btn btn-primary m-btn m-btn--custom m-btn--icon m-btn--air m-btn--pill" onclick="javascript: loadModalInInsertMode();">
                            @*data-toggle="modal" data-target="#m_maxlength_modal">*@
                            <span>
                                <i class="la la-plus"></i>
                                <span>New</span>
                            </span>
                        </a>
                        <div class="m-separator m-separator--dashed d-xl-none"></div>
                    </div>
                </div>
            </div>

            <div class="tag_datatable" id="ajax_data"></div>

        </div>

    </div>

    <div class="modal fade blockui_modal" id="m_maxlength_modal" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">

                <div class="modal-header">
                    <h5 class="modal-title" id="">New Tag</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true" class="la la-remove"></span>
                    </button>
                </div>

                <form id="save_information" class="m-form m-form--fit m-form--label-align-right">
                    <div class="modal-body">
                        <input type='hidden' id="Id" />
                        <div class="form-group m-form__group row m--margin-top-20">
                            <label class="col-form-label col-lg-3 col-sm-12">Title</label>
                            <div class="col-lg-9 col-md-9 col-sm-12">
                                <input type='text' class="form-control m_maxlength_1_custom" id="Title" maxlength="100" required="required" />
                            </div>
                        </div>
                        <div class="form-group m-form__group row m--margin-top-20">
                            <label class="col-form-label col-lg-3 col-sm-12">Status</label>
                            <div class="col-lg-9 col-md-9 col-sm-12">
                                <select class="form-control m-input m-input--air" id="Status">
                                    <option>Active</option>
                                    <option>Inactive</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-brand m-btn" data-dismiss="modal">Close</button>
                        <button id="btnSave" type="button" class="btn btn-secondary m-btn">Submit</button>
                    </div>
                </form>

            </div>
        </div>
    </div>

    @section page_styles {
        <link href="~/assets/vendors/custom/datatables/datatables.bundle.css" rel="stylesheet" type="text/css" />
    }

    @section Scripts {
        <script src="~/vendors/bootstrap-maxlength/src/bootstrap-maxlength.js" type="text/javascript"></script>
        <script src="~/assets/demo/default/custom/crud/forms/widgets/bootstrap-maxlength.js" type="text/javascript"></script>
        <script src="~/js/BlockUI_Custom.js"></script>
        <script>

        jQuery(document).ready(function() {
            initTagDatatable();
            formValidation();
        });

        var initTagDatatable = function() {
            var datatable = $('.tag_datatable').mDatatable({
                data: {
                    type: 'remote',
                    source: {
                        read: {
                            url: "@(@Url.Action("GetTagList", "Tag", new {Area = "Master"}))",
                            map: function(raw) {
                                var dataSet = raw;
                                if (typeof raw.data !== 'undefined') {
                                    dataSet = raw.data;
                                }
                                return dataSet;
                            }
                        }
                    },
                    pageSize: 10,
                    serverPaging: true,
                    serverFiltering: true,
                    serverSorting: true
                },

                layout: {
                    scroll: false,
                    footer: false
                },

                sortable: true,

                pagination: true,

                toolbar: {
                    placement: ['bottom'],
                    items: {
                        pagination: {
                            pageSizeSelect: [10, 20, 30, 40, 50, 100]
                        }
                    }
                },

                search: {
                    input: $('#generalSearch')
                },

                columns: [
                    {
                        field: 'id',
                        title: 'Id',
                        sortable: 'asc', // default sort
                        filterable: false // disable or enable filtering
                        //template: '{{OrderID}} - {{ShipCountry}}',
                    },
                    {
                        field: 'title',
                        title: 'Title'
                    },
                    {
                        field: 'createdDate',
                        title: 'Created date',
                        type: 'date',
                        format: 'MM/DD/YYYY'
                    },
                    {
                        field: 'status',
                        title: 'Status',
                        //sortable: false,
                        template: function(row) {
                            var status = {
                                'Active': { 'title': 'Active', 'class': ' m-badge--success' },
                                'Inactive': { 'title': 'Inactive', 'class': ' m-badge--danger' },
                            };
                            return '<span class="m-badge ' +
                                status[row.status].class +
                                ' m-badge--wide">' +
                                status[row.status].title +
                                '</span>';
                        }
                    },
                    {
                        field: 'Actions',
                        title: 'Actions',
                        sortable: false,
                        overflow: 'visible',
                        template: function(row, index, datatable) {
                            return "<a href=\"javascript: loadModalInEditMode('" +
                                row.id +
                                "');\" class=\"m-portlet__nav-link btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill\" title=\"Edit details\"><i class=\"la la-edit\"></i></a> <a onclick=\"javascript:if (confirm('Are you sure you want to delete?') == false) return false; Delete('" +
                                row.id +
                                "');\" class=\"m-portlet__nav-link btn m-btn m-btn--hover-danger m-btn--icon m-btn--icon-only m-btn--pill\" title=\"Delete details\"><i class=\"la la-trash\"></i></a>";
                        }
                    }
                ]
            });

            $('#m_form_status').on('change',
                function() {
                    datatable.search($(this).val(), 'Status');
                });

            //$('#m_form_type').on('change', function () {
            //    datatable.search($(this).val(), 'Type');
            //});

            //$('#m_form_status, #m_form_type').selectpicker();

        };

        function formValidation() {
            $("#btnSave").on("click",
                function () {
                    if ($("#save_information")[0].checkValidity()) {
                        saveData();
                    } else {
                        $("#save_information")[0].reportValidity();
                    }
                });
        }

        function loadModalInInsertMode() {
            $("#Id").val("");
            $("#Title").val("");
            $("select#Status").val('Active');
            $("#m_maxlength_modal").modal();
        }

        function loadModalInEditMode(id) {
            $.ajax({
                type: "GET",
                cache: false,
                url: "@(@Url.Action("GetTag", "Tag", null))",
                data: {"Id": id},
                dataType: "html",
                success: function(result) {
                    var parseData = JSON.parse(result);
                    var footerLink = parseData.value;
                    $("#Id").val(footerLink.id);
                    $("#Title").val(footerLink.title);
                    $("select#Status").val(footerLink.status);
                    $("#m_maxlength_modal").modal();
                },
                error: function(error) {
                    var msg = 'Fail to load tag.';
                    alert(msg);
                }
            });
        }

        function saveData() {
            blockUI_Modal();
            var fd = new FormData();
            fd.append("Id", $("#Id").val());
            fd.append("Title", $("#Title").val());
            fd.append("Status", $("#Status :selected").val());
            $.ajax({
                type: "POST",
                url: "@(@Url.Action("InsertUpdate", "Tag", new {Area = "Master"}))",
                data: fd,
                cache: false,
                contentType: false,
                processData: false,
                success: function(data, textStatus) {
                    $("#m_maxlength_modal .close").click();
                    $("#Id").val("");
                    $("#Title").val("");
                    $("select#Status").val('Active');
                    unblockUI_Modal();
                    $('.tag_datatable').mDatatable().search('', 'Status');
                },
                failure: function(response) {
                    //alert(response.responseText);
                    unblockUI_Modal();
                },
                error: function(XMLHttpRequest, textStatus) {
                    //alert(textStatus);
                    unblockUI_Modal();
                }
            });
        }

        function Delete(id) {
            blockUI_Page();
            var fd = new FormData();
            fd.append("Id", id);
            $.ajax({
                type: "DELETE",
                url: "@(@Url.Action("Delete", "Tag", new {Area = "Master"}))",
                data: fd,
                cache: false,
                contentType: false,
                processData: false,
                success: function(data) {
                    $('.tag_datatable').mDatatable().search('', 'Status');
                    if (data.success)
                        alert(data.message);
                    else
                        alert(data.message);
                },
                failure: function(response) {
                },
                error: function(XMLHttpRequest, textStatus) {
                }
            });
            unblockUI_Page();
        }
        </script>

    }