Sppages1.0.1/Sppages.UserInterface/Areas/Menus/Controllers/FooterLinkController.cs
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using Invoice.Service.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Sppages.Business.Derived;
using Sppages.Business.Utility;
using Sppages.Model.Factories;
using Sppages.Model.Master;
using Sppages.Model.Menus;

namespace Sppages.UserInterface.Areas.Menus.Controllers
{
    [Area("Menus")]
    [Authorize(Roles = "SMAdmin, Admin")]
    public class FooterLinkController : Controller
    {
        private readonly BllFooterLink _bllFooterLink;

        public FooterLinkController(IMenuService iMenuService, IModelFactory iModelFactory)
        {
            _bllFooterLink = new BllFooterLink(iMenuService, iModelFactory);
        }

        public async Task<IActionResult> Index()
        {
            //var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value; // will give the user's userId
            //var userName = User.FindFirst(ClaimTypes.Name).Value; // will give the user's userName
            //var userEmail = User.FindFirst(ClaimTypes.Email).Value; // will give the user's Email
            //ViewBag.LoadParent=LoadParent();
            //ViewBag.LoadLocation=LoadLocation();
            return View();
        }

        [HttpGet]
        public async Task<IList<FooterLinkSummaryModel>> LoadParent()
        {
            return await _bllFooterLink.LoadParent();
        }

        [HttpGet]
        public async Task<IList<LocationSummaryModel>> LoadLocation()
        {
            return await _bllFooterLink.LoadLocation();
        }

        [HttpPost]
        public async Task<JsonResult> GetFooterLinkList(IFormCollection formFields)
        {
            return Json(await _bllFooterLink.GetFooterLinkList(formFields));
        }

        [HttpGet]
        public async Task<JsonResult> GetFooterLink(string Id)
        {
            var footerLink = await _bllFooterLink.GetFooterLink(Id);
            return Json(new
            {
                Success = true,
                Value = footerLink
            });
        }

        [HttpPost]
        public async Task<JsonResult> InsertUpdate(FooterLinkModel footerLinkModel)
        {
            if (ModelState.IsValid)
                try
                {
                    if (footerLinkModel.Id != null)
                    {
                        footerLinkModel.ModifiedBy = User.FindFirst(ClaimTypes.Name).Value;
                        await _bllFooterLink.Update(footerLinkModel);
                    }
                    else
                    {
                        footerLinkModel.Id = await _bllFooterLink.GetFooterLinkId();
                        footerLinkModel.CreatedBy = User.FindFirst(ClaimTypes.Name).Value;
                        await _bllFooterLink.Insert(footerLinkModel);
                    }
                    return Json(new { success = true, Message = MessageManager.FOOTER_LINK_SAVE_SUCCESS_MESSAGE });
                }
                catch (Exception ex)
                {
                }
            return Json(new { success = true, Message = MessageManager.FOOTER_LINK_SAVE_FAIL_MESSAGE });
        }

        [HttpDelete]
        public async Task<JsonResult> Delete(string Id)
        {
            if (ModelState.IsValid)
                try
                {
                    var result = await _bllFooterLink.Delete(Id);
                    if (result)
                        return Json(new
                        {
                            Success = true,
                            Message = MessageManager.FOOTER_LINK_DELETE_SUCCESS_MESSAGE
                        });
                    return Json(new
                    {
                        Success = false,
                        Message = MessageManager.FOOTER_LINK_DELETE_FAIL_MESSAGE
                    });
                }
                catch (Exception ex)
                {
                    throw ex;
                }
            return Json(new
            {
                Success = false,
                Message = MessageManager.FOOTER_LINK_DELETE_FAIL_MESSAGE
            });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                // db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

Sppages1.0.1/Sppages.UserInterface/Areas/Menus/Views/FooterLink/Index.cshtml
@model IEnumerable<Sppages.Model.Menus.FooterLinkModel>
@{
    ViewBag.Title = "Footer Link Management";
    Layout = "_LayoutBackEnd";
}

<div class="m-portlet m-portlet--mobile">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <h3 class="m-portlet__head-text">
                    @ViewBag.Title
                </h3>
            </div>
        </div>
        <div class="m-portlet__head-tools">
            <ul class="m-portlet__nav"><li class="m-portlet__nav-item"></li></ul>
        </div>
    </div>

    <div class="m-portlet__body">

        <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
            <div class="row align-items-center">
                <div class="col-xl-8 order-2 order-xl-1">
                    <div class="form-group m-form__group row align-items-center">
                        <div class="col-md-4">
                            <div class="m-form__group m-form__group--inline">
                                <div class="m-form__label">
                                    <label>Status:</label>
                                </div>
                                <div class="m-form__control">
                                    <select class="form-control m-bootstrap-select1" id="m_form_status">
                                        <option value="All">All</option>
                                        <option value="Active">Active</option>
                                        <option value="Inactive">Inactive</option>
                                    </select>
                                </div>
                            </div>
                            <div class="d-md-none m--margin-bottom-10"></div>
                        </div>

                        <div class="col-md-4">
                            <div class="m-input-icon m-input-icon--left">
                                <input type="text" class="form-control m-input" placeholder="Search..." id="generalSearch">
                                <span class="m-input-icon__icon m-input-icon__icon--left">
                                    <span><i class="la la-search"></i></span>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-4 order-1 order-xl-2 m--align-right">
                    <a href="#" class="btn btn-primary m-btn m-btn--custom m-btn--icon m-btn--air m-btn--pill" onclick="javascript: loadModalInInsertMode();">
                        @*data-toggle="modal" data-target="#m_maxlength_modal">*@
                        <span>
                            <i class="la la-plus"></i>
                            <span>New</span>
                        </span>
                    </a>
                    <div class="m-separator m-separator--dashed d-xl-none"></div>
                </div>
            </div>
        </div>

        <div class="footer_link_datatable" id="ajax_data"></div>

    </div>

</div>

<div class="modal fade blockui_modal" id="m_maxlength_modal" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title" id="">New Footer Link</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true" class="la la-remove"></span>
                </button>
            </div>

            <form id="save_information" class="m-form m-form--fit m-form--label-align-right">
                <div class="modal-body">
                    <input type='hidden' id="Id" />
                    <div class="form-group m-form__group row m--margin-top-20">
                        <label class="col-form-label col-lg-3 col-sm-12">Name</label>
                        <div class="col-lg-9 col-md-9 col-sm-12">
                            <input type='text' class="form-control m_maxlength_1_custom" id="Name" maxlength="100" required="required" />
                        </div>
                    </div>

                    <div class="form-group m-form__group row m--margin-top-20">
                        <label class="col-form-label col-lg-3 col-sm-12">Url</label>
                        <div class="col-lg-9 col-md-9 col-sm-12">
                            <input type='text' class="form-control m_maxlength_1_custom" id="Url" maxlength="100" required="required" />
                        </div>
                    </div>

                    <div class="form-group m-form__group row m--margin-top-20">
                        <label class="col-form-label col-lg-3 col-sm-12">Order</label>
                        <div class="col-lg-9 col-md-9 col-sm-12">
                            <input type='text' class="form-control m_maxlength_1_custom" id="Order" maxlength="10"/>
                        </div>
                    </div>

                    <div class="form-group m-form__group row m--margin-top-20">
                        <label class="col-form-label col-lg-3 col-sm-12">Status</label>
                        <div class="col-lg-9 col-md-9 col-sm-12">
                            <select class="form-control m-input m-input--air" id="Status">
                                <option>Active</option>
                                <option>Inactive</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button id="btnSave" type="button" class="btn btn-brand m-btn">Save</button>
                    <button type="button" class="btn btn-secondary m-btn" data-dismiss="modal">Close</button>
                </div>
            </form>

        </div>
    </div>
</div>

@Html.Hidden("footerLinkListUrl", Url.Action("GetFooterLinkList", "FooterLink", new { Area = "Menus" }))
@Html.Hidden("loadLocationUrl", Url.Action("LoadLocation", "FooterLink", null))
@Html.Hidden("loadParentUrl", Url.Action("LoadParent", "FooterLink", null))

@Html.Hidden("loadParentUrl", Url.Action("LoadParent", "FooterLink", null))
@Html.Hidden("getFooterListUrl", Url.Action("GetFooterLink", "FooterLink", null))

@Html.Hidden("insertUpdateUrl", Url.Action("InsertUpdate", "FooterLink", new { Area = "Menus" }))

@Html.Hidden("deleteUrl", Url.Action("Delete", "FooterLink", new { Area = "Menus" }))

@section page_styles {
    <link href="~/assets/vendors/custom/datatables/datatables.bundle.css" rel="stylesheet" type="text/css" />
}

@section Scripts {
    <script src="~/vendors/bootstrap-maxlength/src/bootstrap-maxlength.js" type="text/javascript"></script>
    <script src="~/assets/demo/custom/crud/forms/widgets/bootstrap-maxlength.js" type="text/javascript"></script>
    <script src="~/js/BlockUI_Custom.js"></script>

    <script src="~/js/FooterLink.js"></script>

    <script>


    </script>

}